// <auto-generated />
using Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseService))]
    [Migration("20190623005253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Entities.Appointment", b =>
                {
                    b.Property<Guid>("AppointmentId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppointmentDate");

                    b.Property<Guid?>("AppointmentIntervalId");

                    b.Property<Guid>("DoctorId");

                    b.Property<bool>("HaveFeedback");

                    b.Property<bool>("HaveMedicalHistory");

                    b.Property<Guid>("PatientId");

                    b.HasKey("AppointmentId");

                    b.HasIndex("AppointmentIntervalId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("Core.Entities.AppointmentInterval", b =>
                {
                    b.Property<Guid>("AppointmentIntervalId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Day");

                    b.Property<Guid>("DoctorId");

                    b.Property<TimeSpan>("EndHour");

                    b.Property<TimeSpan>("StartHour");

                    b.HasKey("AppointmentIntervalId");

                    b.HasIndex("DoctorId");

                    b.ToTable("AppointmentIntervals");
                });

            modelBuilder.Entity("Core.Entities.BloodDonor", b =>
                {
                    b.Property<Guid>("BloodDonorId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("PatientId");

                    b.Property<string>("Type");

                    b.HasKey("BloodDonorId");

                    b.ToTable("BloodDonors");
                });

            modelBuilder.Entity("Core.Entities.Doctor", b =>
                {
                    b.Property<Guid>("DoctorId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("DIN");

                    b.Property<string>("Description");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("Hospital");

                    b.Property<bool>("IsMale");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.Property<string>("Speciality");

                    b.HasKey("DoctorId");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Core.Entities.Feedback", b =>
                {
                    b.Property<Guid>("FeedbackId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AppointmentDate");

                    b.Property<string>("Description");

                    b.Property<Guid>("DoctorId");

                    b.Property<Guid>("PatientId");

                    b.Property<int>("Rating");

                    b.Property<DateTime>("ReviewDate");

                    b.HasKey("FeedbackId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Core.Entities.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Birthdate");

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<Guid>("HistoryId");

                    b.Property<string>("LastName");

                    b.Property<string>("NIN");

                    b.Property<string>("Password");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("PatientId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("Core.Entities.PatientHistory", b =>
                {
                    b.Property<Guid>("HistoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Allergies");

                    b.Property<string>("Consultations");

                    b.Property<string>("Drink");

                    b.Property<string>("Gender");

                    b.Property<string>("HealthConditions");

                    b.Property<string>("Height");

                    b.Property<DateTime?>("LastVisit");

                    b.Property<Guid>("PatientId");

                    b.Property<string>("Smoke");

                    b.Property<string>("Weight");

                    b.HasKey("HistoryId");

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("PatientHistories");
                });

            modelBuilder.Entity("Core.Entities.Appointment", b =>
                {
                    b.HasOne("Core.Entities.AppointmentInterval", "AppointmentInterval")
                        .WithMany("Appointments")
                        .HasForeignKey("AppointmentIntervalId");

                    b.HasOne("Core.Entities.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.AppointmentInterval", b =>
                {
                    b.HasOne("Core.Entities.Doctor")
                        .WithMany("AppointmentIntervals")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.Feedback", b =>
                {
                    b.HasOne("Core.Entities.Doctor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithMany("Feedbacks")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Entities.PatientHistory", b =>
                {
                    b.HasOne("Core.Entities.Patient", "Patient")
                        .WithOne("PatientHistory")
                        .HasForeignKey("Core.Entities.PatientHistory", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
